services:
  catalogdb:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    ports:
      - "8080:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data